/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

/**
 *
 * @author Adim
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        etatLogin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonConnexion = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        inputCompte = new javax.swing.JTextField();
        inputMdp = new javax.swing.JTextField();
        etatLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonConnexion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        buttonConnexion.setText("Connexion");
        buttonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnexionActionPerformed(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("Login");

        inputCompte.setText("Nom de compte");
        inputCompte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputCompteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCompteFocusLost(evt);
            }
        });

        inputMdp.setText("Mot de passe");
        inputMdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputMdpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputMdpFocusLost(evt);
            }
        });

        etatLogin.setForeground(new java.awt.Color(255, 0, 0));
        etatLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etatLogin.setText("Erreur: bla bla bla bla bla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonConnexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(inputMdp))
                            .addGap(97, 97, 97)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etatLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etatLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(buttonConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnexionActionPerformed
        // TODO add your handling code here:
        if( inputCompte.getText().equals("Nom de compte") || inputMdp.getText().equals("Mot de passe") || inputCompte.getText().isEmpty() || inputMdp.getText().isEmpty())
        {
            etatLogin.setText("Identifiant vide.");
            etatLogin.setVisible(true);
        }
    }//GEN-LAST:event_buttonConnexionActionPerformed

    private void inputCompteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCompteFocusLost
        // TODO add your handling code here:
         if (inputCompte.getText().isEmpty()) 
         {
            inputCompte.setText("Nom de compte");
         }
    }//GEN-LAST:event_inputCompteFocusLost

    private void inputCompteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCompteFocusGained
        // TODO add your handling code here:
        if (inputCompte.getText().equals("Nom de compte")) {
            inputCompte.setText("");
        }
    }//GEN-LAST:event_inputCompteFocusGained

    private void inputMdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputMdpFocusLost
        // TODO add your handling code here:
        if (inputMdp.getText().isEmpty()) 
         {
            inputMdp.setText("Mot de passe");
         }
    }//GEN-LAST:event_inputMdpFocusLost

    private void inputMdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputMdpFocusGained
        // TODO add your handling code here:
         if (inputMdp.getText().equals("Mot de passe")) {
            inputMdp.setText("");
        }
    }//GEN-LAST:event_inputMdpFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnexion;
    private javax.swing.JLabel etatLogin;
    private javax.swing.JTextField inputCompte;
    private javax.swing.JTextField inputMdp;
    private javax.swing.JLabel labelLogin;
    // End of variables declaration//GEN-END:variables
}
